### ISSUE TITLE
VM keeps kicking me out, then ask for a password then work normal 

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/zos#1486]
While working on deploying a VM out of nothing, it kicked me out, then asked for a password, then it allowed me in.
this scenario keeps happening with this VM

![image](https://user-images.githubusercontent.com/46320202/143428899-73046645-0a91-4d56-b787-ec0e1676b3d9.png)
![image](https://user-images.githubusercontent.com/46320202/143428680-0bc76bfe-7c25-4d7a-a05b-eac391824885.png)
![image](https://user-images.githubusercontent.com/46320202/143428700-7591426c-90e1-4eb5-8eaf-af423708d4fe.png)
VM Information
```
{
    version: 0,
    name: 'testvm',
    created: 1637833227,
    status: 'ok',
    message: '',
    flist: 'https://hub.grid.tf/samehabouelsaad.3bot/tf-caprover-main-a4f186da8d.flist',
    publicIP: { ip: '185.206.122.35/24', gateway: '185.206.122.1' },
    planetary: false,
    yggIP: '',
    interfaces: [ { network: 'wedtest', ip: '10.249.4.2' } ],
    capacity: { cpu: 1, memory: 2048 },
    mounts: [
      {
        name: 'wedDisk',
        mountPoint: '/testdisk',
        size: 8589934592,
        state: 'ok',
        message: ''
      }
    ],

```

``` contract Data
contracts: {
    created: [
      {
        version: 1,
        state: 'Created',
        contract_id: 1125,
        twin_id: 70,
        contract_type: {
          nodeContract: {
            node_id: 17,
            deployment_data: '0x',
            deployment_hash: '0x3161626435376436373165363332653332613261313864636131623062356231',
            public_ips: 1,
            public_ips_list: [
              {
                ip: '0x3138352e3230362e3132322e33352f3234',
                gateway: '0x3138352e3230362e3132322e31',
                contract_id: 1125
              }
            ]
          }
        }
      }
    ],

```

**Comment by OmarElawady** [comment]
Executing this from a node in the farm:
```bash
# many times to see if the mac differs
ip netns exec public ip neigh flush 185.206.122.35
ip netns exec public ping -c 1 185.206.122.35
ip netns exec public ip neigh | grep 35
# these ips were printed
# 185.206.122.35 dev public lladdr ce:65:be:56:e6:55 REACHABLE
# 185.206.122.35 dev public lladdr ba:ff:41:b2:d7:b9 REACHABLE
```
Only two contracts I found on polka holding this ip:
Contract id: 585, state: Deleted, node id: 17
Contract id: 1125, state: Created, node id: 11

**Comment by muhamadazmy** [comment]
Sounds like another conflicting IP. this IP must be actively used by other VMs or devices on the same network. Will try to find out what is using it

**Comment by delandtj** [comment]
huh... you have 2 entries in your neighbor table ??????? wtaf! and reachable even! wtf wtf wtf... thats a linx bugggg

**Comment by muhamadazmy** [comment]
There are 2 VMs that are using the same public ip in devnet. I will look into how this happened.

**Comment by OmarElawady** [comment]
> huh... you have 2 entries in your neighbor table ??????? wtaf! and reachable even! wtf wtf wtf... thats a linx bugggg

Not at the same time no :D I kept flushing and pinging the ip to see if the mac differs and it produced these two macs after different flushes.

**Comment by muhamadazmy** [comment]
It seems the VM from contract `585` was never destroyed.

**Comment by muhamadazmy** [comment]
Seems the node has missed some decomission events from the chain because of some new type of event introduced to the chain 
![image](https://user-images.githubusercontent.com/10920323/143446022-5f50b1fc-5883-497f-b23e-d98fa30bd8f5.png)


@DylanVerstraete ?

**Comment by muhamadazmy** [comment]
So `eventually` the node managed to delete the contact. So the conflict should be automatically resolved now. Fixing the events unmarshaling caused by this unknown event type will make the node react faster to cancelled contracts

**Comment by sameh-farouk** [comment]
can we harden this or have it listed as a know limitation somewhere? I hit this issue multiple times today, where Yggdrasil worked fine while ipv4 was asking for the password, but it works eventually. I saw also this [issue](https://github.com/threefoldtech/grid_weblets/issues/166), the OP said [here](https://github.com/threefoldtech/grid_weblets/issues/166#issuecomment-993588506) he has deleted all the deployed instances except the last one, but he forgot to update the DNS record to refer to the new VM IP address, however, he was able to access the old instance through the old IP although he deleted all his deployments while ago. so it looks like the same issue too.

**Comment by sameh-farouk** [comment]
this keeps happening to me for two days now. can't have a stable connection to my VM. same behavior the OP explained here. Yggdrasil IP works with no issue. this happens the whole day with the deployment below and happens as well with other deployments yesterday alot.

{
  version: 1
  state: Created
  contract_id: 3,282
  twin_id: 132
  contract_type: {
    NodeContract: {
      node_id: 1
      deployment_data: 
      deployment_hash: 19516d0dd99b28896b7bd148f1406901
      public_ips: 1
      public_ips_list: [
        {
          ip: 185.206.122.39/24
          gateway: 185.206.122.1
          contract_id: 3,282
        }
      ]
    }
  }
}

**Comment by OmarElawady** [comment]
There was an [issue](https://github.com/threefoldtech/zos/issues/1514) with contract reporting that caused vms with deleted contracts to not get decommissioned. Should be fixed.

**Comment by sameh-farouk** [comment]
Great, Is that fix pushed to the nodes already? Or it's expected to have this error from time to time till a new release or something?

**Comment by OmarElawady** [comment]
pushed to devnet and testnet

**Comment by sameh-farouk** [comment]
@OmarElawady I still face the same issue with the same contract mentioned above.

![Screenshot from 2021-12-21 17-03-20](https://user-images.githubusercontent.com/42457449/146951711-64629722-ddc6-4246-a224-340d949da2a6.png)

**Comment by sameh-farouk** [comment]
@OmarElawady @muhamadazmy thought there were fixe/s pushed that should fix this issue, I'm still can't maintain access to this deployment through the ipv4 address, it won't last longer than a minute before kicking me out. I don't want to delete this deployment so we have a chance to debug this issue and verify any possible fix. let me know if i should delete it instead and release this IP for good :D

**Comment by dumblob** [comment]
@sameh-farouk does this still happen to you?

**Comment by sameh-farouk** [comment]
No, this didn't happened for sometime now.
