### ISSUE TITLE
Data loss on a Grid VM, probably because of a Node restart.

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/zos#1672]
spot a wired behavior on a gird VM
I had a VM deployed 2 days ago, 26 Apr I recall correctly.
today I noted:
- host key for the VM has changed.
- created epoch timestamp in the deployment JSON refers to 30 minutes ago.
- **data in the VM was wiped.**

seems the VM has restarted.

```
{
    "version": 0,
    "contractId": 744,
    "nodeId": 1,
    "name": "VMedc159c9",
    "created": 1651151823,
    "status": "ok",
    "message": "",
    "flist": "https://hub.grid.tf/tf-official-vms/ubuntu-20.04-lts.flist",
    "publicIP": {
        "ip": "185.206.122.38/24",
        "ip6": "",
        "gateway": "185.206.122.1"
    },
    "planetary": "301:a9bd:9b77:ce71:5705:70b:3185:1a1e",
    "interfaces": [
        {
            "network": "NW05f67022",
            "ip": "10.20.2.2"
        }
    ],
    "capacity": {
        "cpu": 4,
        "memory": 8192
    },
    "mounts": [
        {
            "name": "DISK6ea0d8ca",
            "mountPoint": "/mnt/disk6ea0d8ca",
            "size": 53687091200,
            "state": "ok",
            "message": ""
        }
    ],
    "env": {
        "SSH_KEY": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC9MI7fh4xEOOEKL7PvLvXmSeRWesToj6E26bbDASvlZnyzlSKFLuYRpnVjkr8JcuWKZP6RQn8+2aRs6Owyx7Tx+9kmEh7WI5fol0JNDn1D0gjp4XtGnqnON7d0d5oFI+EjQQwgCZwvg0PnV/2DYoH4GJ6KPCclPz4a6eXrblCLA2CHTzghDgyj2x5B4vB3rtoI/GAYYNqxB7REngOG6hct8vdtSndeY1sxuRoBnophf7MPHklRQ6EG2GxQVzAOsBgGHWSJPsXQkxbs8am0C9uEDL+BJuSyFbc/fSRKptU1UmS18kdEjRgGNoQD7D+Maxh1EbmudYqKW92TVgdxXWTQv1b1+3dG5+9g+hIWkbKZCBcfMe4nA5H7qerLvoFWLl6dKhayt1xx5mv8XhXCpEC22/XHxhRBHBaWwSSI+QPOCvs4cdrn4sQU+EXsy7+T7FIXPeWiC2jhFd6j8WIHAv6/rRPsiwV1dobzZOrCxTOnrqPB+756t7ANxuktsVlAZaM= sameh@sameh-inspiron-3576"
    },
    "entrypoint": "/init.sh",
    "metadata": "",
    "description": "",
    "corex": false
}
```

**Comment by coesensbert** [comment]
I might have experienced something similar here https://github.com/threefoldtech/zos/issues/1648

**Comment by muhamadazmy** [comment]
I think i know why, I will try to locate the bug and update this issue

**Comment by muhamadazmy** [comment]
The bug was fixed, and currently deploying on devnet. Please close after verification. You probably need to give it sometime until it's fully deployed before retrying

**Comment by muhamadazmy** [comment]
@sameh-farouk can you confirm and close this issue

**Comment by sameh-farouk** [comment]
@muhamadazmy will verify it today isa

**Comment by sameh-farouk** [comment]
Hi, how to verify this one without a node restart? 

is restarting the VM sufficient?

**Comment by sameh-farouk** [comment]
**verified** on ef480d329f8f268d9e6ee148bb3e7a2d6aaf292f. tested on Devnet with VM on node 3 . data still exists after rebooting the node.
